from tkinter import *
def main():
    User_login = Tk()
    userid = StringVar()
    paswrd = StringVar()
    def some():
        name = userid.get()
        pass_wrd = paswrd.get()
        print("The name is : " + name)
        print("The password is : " + pass_wrd)
        userid.set("")
        paswrd.set("")
    User_login.title("Login")
    Label(User_login, text='UserName', width=50, height=2).grid(row=0, column=0)
    Label(User_login, text='Password', width=50, height=2).grid(row=1, column=0)
    e1 = Entry(User_login, bd=5, textvariable=userid)
    e2 = Entry(User_login, bd=5, textvariable=paswrd, show='*')
    login = Button(User_login, text='Login', command=some, width=100, height=2, bd=5)
    go_back = Button(User_login, text='Go Back', command=User_login.destroy, width=100, height=2, bd=5)
    e1.grid(row=0, column=1, padx=100, pady=4)
    e2.grid(row=1, column=1, padx=100, pady=4)
    login.grid(row=2, columnspan=2, padx=100, pady=4)
    go_back.grid(row=3, columnspan=2, padx=100, pady=4)
    User_login.mainloop()
